[tool.poetry]
name = "plc4x"
version = "0.1.0"
description = ""
authors = ["ottlukas <ott.lukas.14@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
